plugins {
    id 'kronor.android.application'
    id 'kronor.android.compose'
    alias(libs.plugins.apollo)
    alias(libs.plugins.kotlin.serialization)
}

def kronorMerchantToken = project.hasProperty('KRONOR_MERCHANT_TOKEN') ? project.property('KRONOR_MERCHANT_TOKEN') : System.getenv('KRONOR_MERCHANT_TOKEN') ?: ''
def escapedKronorMerchantToken = kronorMerchantToken
        .replace('\\', '\\\\')
        .replace('"', '\\"')

if (!escapedKronorMerchantToken) {
    throw new GradleException("KRONOR_MERCHANT_TOKEN is missing")
}

android {
    namespace = 'io.kronor.example'

    defaultConfig {
        applicationId 'io.kronor.example'
        versionCode 1
        versionName '1.0'
        buildConfigField('String', 'KRONOR_MERCHANT_TOKEN', "\"${escapedKronorMerchantToken}\"")
    }

    buildFeatures.buildConfig = true
}

apollo {
    service('service') {
        packageName.set('io.kronor.example')
        introspection {
            endpointUrl.set('https://staging.kronor.io/v1/graphql')
            schemaFile.set(file('src/main/graphql/schema.graphqls'))
            headers.put('Authorization', "Bearer ${kronorMerchantToken}")
        }
    }
}

dependencies {
    implementation libs.androidx.core
    implementation libs.androidx.appcompat
    implementation libs.google.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.navigation3.runtime
    implementation libs.androidx.navigation3.ui
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.lifecycle.viewmodel.navigation3
    implementation libs.androidx.activity.compose
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.material
    implementation libs.androidx.compose.material3
    implementation libs.apollo.runtime
    implementation libs.kotlinx.serialization.core

    testImplementation libs.junit4
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest
    lintChecks libs.compose.lint.checks

    implementation project(':kronor_swish')
    implementation project(':kronor_api')
    implementation project(':kronor_credit_card')
    implementation project(':kronor_webview_payment_gateway')
    implementation project(':kronor_mobilepay')
    implementation project(':kronor_vipps')
    implementation project(':kronor_paypal')
    implementation project(':kronor_bank_transfer')
    implementation project(':kronor_fallback')
    implementation project(':kronor_googlepay')
}
