plugins {
    id 'kronor.android.published-library'
    id 'kronor.android.compose'
}

kronorPublishing {
    groupId.set('io.kronor.component')
    artifactId.set('webview_payment_gateway')
    displayName.set('webview_payment_gateway')
    description.set('Kronor common component for Kronor API')
}

android {
    namespace = 'io.kronor.component.webview_payment_gateway'
    lint.disable.add('MissingTranslation')
}

dependencies {
    implementation libs.androidx.webkit
    implementation libs.androidx.compose.animation
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.lifecycle.runtime.compose
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.material
    implementation libs.statemachine
    implementation libs.apollo.api

    testImplementation libs.junit4
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest
    lintChecks libs.compose.lint.checks

    api project(':kronor_api')
}
