plugins {
    id 'kronor.android.published-library'
    id 'kronor.android.compose'
}

kronorPublishing {
    groupId.set('io.kronor.component')
    artifactId.set('swish')
    displayName.set('swish')
    description.set('Kronor Swish Component for Kronor API')
}

android {
    namespace = 'io.kronor.component.swish'
    lint.disable.add('MissingTranslation')
}

dependencies {
    implementation libs.androidx.compose.animation
    implementation libs.androidx.navigation.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.material
    implementation libs.apollo.api
    implementation libs.zxing
    implementation libs.statemachine

    testImplementation libs.junit4
    androidTestImplementation libs.androidx.test.ext.junit
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest
    lintChecks libs.compose.lint.checks

    api project(':kronor_api')
}
