plugins {
    id 'kronor.android.published-library'
    alias(libs.plugins.apollo)
}

def kronorSdkVersion = project.hasProperty('VERSION') ? project.property('VERSION') : System.getenv('KRONOR_SDK_VERSION') ?: 'dev'

kronorPublishing {
    groupId.set('io.kronor')
    artifactId.set('api')
    displayName.set('api')
    description.set('Kronor API component for Kronor SDK')
}

android {
    namespace = 'io.kronor.api'
    defaultConfig {
        buildConfigField('String', 'VERSION', "\"${kronorSdkVersion}\"")
    }
    buildFeatures.buildConfig = true
}

apollo {
    service('service') {
        packageName.set('io.kronor.api')
        mapScalarToKotlinString('bigint')
        mapScalarToKotlinString('uuid')
        mapScalar('timestamptz', 'java.util.Date', 'com.apollographql.adapter.core.DateAdapter')
        schemaFile.set(file('src/main/graphql/schema.graphqls'))
    }
}

dependencies {
    implementation libs.androidx.core
    implementation libs.apollo.runtime
    implementation libs.apollo.adapters.core
    testImplementation libs.junit4
    testImplementation libs.mockwebserver
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
}
