name: Build
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]

# Cancel previous runs of this workflow on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Build components
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set date as version
        run: |
          echo "time=$(date +"%Y%m%d.%H%M")" >> "$GITHUB_ENV"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      # Builds the release artifacts of the library
      - name: Builds all artifacts
        run: ./gradlew clean build
        env:
          ORG_GRADLE_PROJECT_VERSION: ${{ env.time }}